import fs from "node:fs";
import path from "node:path";
import { createHash, randomUUID } from "node:crypto";
import { spawn } from "node:child_process";
import { XMLParser } from "fast-xml-parser";
import { z } from "zod";
import { exportBundle } from "./export";
import { projectComponents } from "./component-integration";
import { bundleHash } from "./validation";
import { StdioStudioClient, resolveRobloxMcpExecutable } from "./studio-mcp-client";
import { isVerifiedClientPlayState, isVerifiedEditState } from "./studio-state";
import { unpackMarketplace } from "../marketplace/studio";
import type { Engine } from "./engine";
import type { Check, Project } from "./schema";

// Acceptance is supplied by the caller before generation, never generated by the
// worker that is being scored. Runtime scripts can perform test actions but must
// not rewrite game sources. This is a local developer API, not an LLM tool.
export const nativeAcceptanceSchema = z.object({
  revision: z.number().int().nonnegative(),
  repair: z.boolean().default(false),
  steps: z.array(z.object({
    id: z.string().regex(/^[a-zA-Z0-9_-]{1,80}$/),
    description: z.string().min(1).max(2000),
    datamodel: z.enum(["Client", "Server"]),
    keys: z.array(z.string().regex(/^[A-Za-z0-9]+$/)).max(30).optional(),
    navigate: z.tuple([z.number().finite(), z.number().finite(), z.number().finite()]).optional(),
    code: z.string().min(1).max(30000),
  }).strict()).min(1).max(40),
}).strict().refine(p => new Set(p.steps.map(s => s.id)).size === p.steps.length, "Duplicate acceptance IDs");
export type NativeAcceptance = z.infer<typeof nativeAcceptanceSchema>;
export interface NativeRuntime {
  open(file: string): Promise<string>;
  call(name: string, args: Record<string, unknown>): Promise<unknown>;
  close(): Promise<void>;
}
const sha = (value: string) => createHash("sha256").update(value).digest("hex");
const pause = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

export function createNativeRuntime(): NativeRuntime {
  const client = new StdioStudioClient({ timeoutMs: 60000 });
  const call = async (name: string, args: Record<string, unknown>) => unpackMarketplace(await client.callTool(name, args));
  return {
    call,
    async open(file) {
      const before = await call("list_roblox_studios", {});
      const ids = new Set((before.studios ?? []).map((s: any) => s.id));
      const executable = path.join(path.dirname(resolveRobloxMcpExecutable()), "RobloxStudioBeta.exe");
      if (!fs.statSync(executable).isFile()) throw Error("Studio executable unavailable");
      const child = spawn(executable, [file], { windowsHide: true, shell: false, stdio: "ignore" });
      let launchError: Error | undefined;
      child.on("error", error => { launchError = error; });
      child.unref();
      for (let attempt = 0; attempt < 60; attempt++) {
        if (launchError) throw launchError;
        const result = await call("list_roblox_studios", {});
        const matches = (result.studios ?? []).filter((s: any) => !ids.has(s.id) && s.name === path.basename(file));
        if (matches.length === 1) return matches[0].id;
        if (matches.length > 1) throw Error("Ambiguous exported Studio identity");
        await pause(1000);
      }
      throw Error("Fresh exported place did not connect within 60 seconds");
    },
    close: () => client.close(),
  };
}

/** A hierarchy/source preflight for the exact file passed to Studio. Duplicate
 * sibling names use ordinal identity, so retained assets are not flattened. */
export function exportManifest(xml: string) {
  const data = new XMLParser({ ignoreAttributes: false, parseTagValue: false, trimValues: false }).parse(xml);
  const list = (v: any): any[] => v === undefined ? [] : Array.isArray(v) ? v : [v];
  const nodes: { address: { name: string; ordinal: number }[]; className: string; source?: string }[] = [];
  const visit = (items: any[], parent: typeof nodes[number]["address"]) => {
    const counts = new Map<string, number>();
    for (const item of items) {
      const name = list(item.Properties?.string).find(p => p["@_name"] === "Name")?.["#text"];
      if (typeof name !== "string") throw Error("Export node missing name");
      const ordinal = (counts.get(name) ?? 0) + 1;
      counts.set(name, ordinal);
      const address = [...parent, { name, ordinal }];
      const sourceProperty = list(item.Properties?.ProtectedString).find(p => p["@_name"] === "Source");
      const source = sourceProperty === undefined ? undefined : String(sourceProperty["#text"] ?? "");
      nodes.push({ address, className: item["@_class"], ...(source === undefined ? {} : { source }) });
      visit(list(item.Item), address);
    }
  };
  visit(list(data.roblox?.Item), []);
  if (!nodes.length) throw Error("Empty export manifest");
  return nodes;
}
export function manifestProbe(xml: string) {
  const encoded = JSON.stringify(JSON.stringify(exportManifest(xml)));
  return `local expected = game:GetService("HttpService"):JSONDecode(${encoded})
local failures = {}
for _, row in ipairs(expected) do
 local current = game
 for _, segment in ipairs(row.address) do
  local count, found = 0, nil
  for _, child in ipairs(current:GetChildren()) do
   if child.Name == segment.name then count += 1 if count == segment.ordinal then found = child break end end
  end
  if not found then current = nil break end
  current = found
 end
 if not current or current.ClassName ~= row.className or (row.source ~= nil and current.Source ~= row.source) then
  table.insert(failures, row.address[#row.address].name)
 end
end
return game:GetService("HttpService"):JSONEncode({passed = #failures == 0, detail = table.concat(failures, ", "), count = #expected})`;
}

export type NativeAttempt = {
  revision: number; artifactHash: string; exportHash: string; exportFile: string;
  planHash: string; studioId?: string; at: string; checks: Check[]; logs: string[];
  outcome: "passed" | "failed" | "environment_failed"; editRestored: boolean;
};
export class NativeAcceptanceRunner {
  readonly active = new Set<string>();
  constructor(private engine: Engine, private directory: string, private runtimeFactory = createNativeRuntime) {}
  async run(id: string, input: NativeAcceptance) {
    const plan = nativeAcceptanceSchema.parse(input);
    const p = this.engine.store.get(id);
    if (this.active.has(id) || p.jobId || this.engine.mutationBlocker?.(id)) throw Error("Project has an active operation");
    if (p.revision !== plan.revision || p.approvedRevision !== p.revision || !p.artifact || !["ready_to_test", "verified"].includes(p.stage) || p.checks.some(c => c.status === "failed")) throw Error("Export requires a current approved build without failed checks");
    this.active.add(id);
    const attempts: NativeAttempt[] = [];
    try {
      for (let round = 0; round < (plan.repair ? 2 : 1); round++) {
        const current = this.engine.store.get(id);
        const result = await this.test(current, plan);
        attempts.push(result);
        const latest = this.engine.store.get(id);
        if (latest.revision !== result.revision || !latest.artifact || bundleHash(latest.artifact) !== result.artifactHash) throw Error("Native result belongs to an obsolete artifact");
        latest.studioEvidence = { revision: result.revision, artifactHash: result.artifactHash, checks: result.checks, logs: result.logs, at: result.at };
        // Preserve the product's truthful ready-to-test label even after scoped checks pass.
        latest.stage = "ready_to_test";
        this.engine.store.save(latest);
        if (result.outcome !== "failed" || !result.editRestored || round === 1 || !plan.repair) break;
        // start() is synchronous, so releasing the lease for this call cannot
        // interleave with an HTTP mutation before Engine takes its own job lock.
        this.active.delete(id);
        try { this.engine.start(id, latest.revision, "repair"); }
        finally { this.active.add(id); }
        await this.engine.wait(id);
        const repaired = this.engine.store.get(id);
        if (repaired.stage !== "ready_to_test" || repaired.checks.some(c => c.status === "failed")) break;
      }
      return { attempts, project: this.engine.store.get(id) };
    } finally { this.active.delete(id); }
  }
  private async test(p: Project, plan: NativeAcceptance): Promise<NativeAttempt> {
    const folder = path.join(this.directory, "native-acceptance", p.id, randomUUID());
    fs.mkdirSync(folder, { recursive: true });
    const xml = exportBundle(p.artifact!, p.scope, projectComponents(p, path.join(this.directory, "asset-evidence", p.id)).map(c => c.xml), p.world, p.rig);
    const file = path.join(folder, "Takko-acceptance-" + path.basename(folder) + ".rbxlx");
    fs.writeFileSync(file, xml, { flag: "wx" });
    fs.writeFileSync(path.join(folder, "plan.json"), JSON.stringify(plan, null, 2), { flag: "wx" });
    const result: NativeAttempt = { revision: p.revision, artifactHash: bundleHash(p.artifact!), exportHash: sha(xml), exportFile: file, planHash: sha(JSON.stringify(plan.steps)), at: new Date().toISOString(), checks: [], logs: [], outcome: "environment_failed", editRestored: false };
    const runtime = this.runtimeFactory();
    let playAttempted = false;
    try {
      result.studioId = await runtime.open(file);
      const args = { studio_id: result.studioId };
      if (!isVerifiedEditState(await runtime.call("get_studio_state", args))) throw Error("Fresh export is not in verified Edit mode");
      const identity = await runtime.call("execute_luau", { ...args, datamodel_type: "Edit", code: manifestProbe(xml) }) as any;
      if (identity?.passed !== true) throw Error("Reopened export hierarchy/source mismatch: " + JSON.stringify(identity));
      playAttempted = true;
      await runtime.call("start_stop_play", { ...args, is_start: true });
      let playing = false;
      for (let attempt = 0; attempt < 20; attempt++) {
        if (isVerifiedClientPlayState(await runtime.call("get_studio_state", args))) { playing = true; break; }
        await pause(500);
      }
      if (!playing) throw Error("Both native client and server are required");
      for (const step of plan.steps) {
        try {
          if (step.navigate) await runtime.call("character_navigation", { ...args, datamodel_type: "Client", x: step.navigate[0], y: step.navigate[1], z: step.navigate[2] });
          if (step.keys?.length) await runtime.call("user_keyboard_input", { ...args, datamodel_type: "Client", actions: step.keys.flatMap(key => [{ action: "keyPress", key_code: key }, { action: "wait", wait_time_ms: 500 }]) });
          const observation = await runtime.call("execute_luau", { ...args, datamodel_type: step.datamodel, code: step.code }) as any;
          const passed = observation?.passed === true && typeof observation.detail === "string";
          result.checks.push({ id: step.id, status: passed ? "passed" : "failed", detail: step.description + ": " + JSON.stringify(observation).slice(0, 12000) });
        } catch (error) { result.checks.push({ id: step.id, status: "failed", detail: step.description + ": " + String(error) }); }
      }
      result.logs.push(JSON.stringify(await runtime.call("get_console_output", args)).slice(0, 30000));
      result.outcome = result.checks.every(c => c.status === "passed") ? "passed" : "failed";
    } catch (error) {
      result.logs.push(String(error));
      result.checks.push({ id: "native-environment", status: "failed", detail: String(error) });
    } finally {
      try {
        if (result.studioId) {
          if (playAttempted) await runtime.call("start_stop_play", { studio_id: result.studioId, is_start: false });
          result.editRestored = isVerifiedEditState(await runtime.call("get_studio_state", { studio_id: result.studioId }));
        }
        if (!result.editRestored) result.outcome = "environment_failed";
      } catch (error) { result.logs.push("Edit restoration failed: " + String(error)); result.outcome = "environment_failed"; }
      try { await runtime.close(); } catch (error) { result.logs.push("MCP close failed: " + String(error)); }
      fs.writeFileSync(path.join(folder, "result.json"), JSON.stringify(result, null, 2), { flag: "wx" });
    }
    return result;
  }
}
