import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {buildSync} from 'esbuild';import {createRequire} from 'node:module';
const dir=path.resolve('.forge/plugin-tests');fs.mkdirSync(dir,{recursive:true});const bin=path.resolve(process.env.LUAU_BIN_DIR??'.forge/tools/luau');const suffix=process.platform==='win32'?'.exe':'';
function run(binary,args){const r=spawnSync(path.join(bin,binary+suffix),args,{encoding:'utf8',windowsHide:true,timeout:20000});if(r.error||r.status!==0)throw Error(r.error?.message??r.stdout+r.stderr);return r.stdout;}
const source=fs.readFileSync('plugin/Forge.plugin.luau','utf8');run('luau-compile',['--null','plugin/Forge.plugin.luau']);
buildSync({entryPoints:['src/generation/base-world.ts'],outfile:path.join(dir,'base-world.cjs'),bundle:true,platform:'node',format:'cjs'});
const {baseWorld}=createRequire(import.meta.url)(path.join(dir,'base-world.cjs'));
const lua=v=>v===null?'nil':typeof v==='string'?JSON.stringify(v):typeof v!=='object'?String(v):Array.isArray(v)?'{'+v.map(lua).join(',')+'}':'{'+Object.entries(v).map(([k,x])=>'['+JSON.stringify(k)+']='+lua(x)).join(',')+'}';
fs.writeFileSync(path.join(dir,'base-world.luau'),'local verifiedBaseWorld='+lua(baseWorld)+'\n');
for (const file of ['tests/project-studio-driver.luau', 'tests/cookie-behavior.luau']) run('luau-compile', ['--null', file]);
const harness=fs.readFileSync(path.join(dir,'base-world.luau'),'utf8')+fs.readFileSync('tests/plugin-mocks.luau','utf8')+'\nlocal function startPlugin()\n'+source+'\nreturn {apply=apply,runTests=runTests,connect=connectToForge,endpoint=endpoint,key=key,status=status,poll=pollOnce,execute=executePending,pending=function() return pending end,outbox=function() return outbox end,session=function() return session end}\nend\nlocal exports=startPlugin()\n'+fs.readFileSync('tests/plugin-assertions.luau','utf8');fs.writeFileSync(path.join(dir,'harness.luau'),harness);const output=run('luau',[path.join(dir,'harness.luau')]);console.log(output.split('SOURCE_BEGIN')[0].trim());let count=0;for(const match of output.matchAll(/SOURCE_BEGIN\r?\n([\s\S]*?)SOURCE_END/g)){const file=path.join(dir,`injected-${++count}.luau`);fs.writeFileSync(file,match[1]);run('luau-compile',['--null',file]);}console.log('COMPILES plugin and '+count+' injected sources. Studio APIs were mocked; no live Studio pass claimed.');

